org: willburket
app: nba-predictions
service: nba-predictions

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11

plugins:
  - serverless-python-requirements

functions:
  hello:
    handler: src.handler.hello

custom:
  pythonRequirements:
    dockerizePip: non-linux
    zip: true 

package:
  # include:
  #   - src/**
  #   - requirements.txt

  exclude:
    - src/data/**

